- name: Install Nagios in Ubuntu
  apt:
    name:
      - nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: start httpd (CentOS)
  service:
    name: httpd
    state: started
  when: ansible_distribution ==  "CentOS"

- name: Install Nagios in CentOS
  dnf:
    name:
      - nagios
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
