---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: update repository index (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: nagios_server
  become: true
  roles:
    - Nagios

- hosts: elasticstack_server
  become: true
  roles:
    - Elastic_Stack

- hosts: igp_server
  become: true
  roles:
    - IGP

- hosts: lampstack_server
  become: true
  roles:
    - Lamp_Stack

